#!/bin/sh
#
# Starts aesdsocket daemon.
#

start() {
        
        printf "Starting aesdsocket daemon: "

        start-stop-daemon -S --name aesdsocket \
                -a /usr/bin/aesdsocket -- -d
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
        printf "Stopping aesdsocket daemon: "
        start-stop-daemon -K --name aesdsocket --signal TERM
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?